import React from 'react';
import { motion } from 'framer-motion';
import SEO from '../components/SEO';
import SafeIcon from '../common/SafeIcon';
import * as LuIcons from 'react-icons/lu';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20 relative z-10">
      <SEO title="Terms of Service | AXiM Systems" description="Legal agreements and terms of service for the AXiM Hub infrastructure." />

      <Link to="/" className="inline-flex items-center gap-2 text-axim-purple hover:text-axim-gold font-mono text-[0.65rem] uppercase tracking-widest transition-colors mb-12 group">
        <SafeIcon icon={LuIcons.LuArrowLeft} className="w-3 h-3 group-hover:-translate-x-1 transition-transform" />
        Return to Hub
      </Link>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, ease: "circOut" }}>
        <header className="mb-12 border-b border-white/10 pb-8">
          <div className="flex items-center gap-2 text-axim-gold font-mono text-xs uppercase tracking-widest mb-4">
            <div className="w-1.5 h-1.5 bg-axim-gold rounded-full" />
            Legal Infrastructure
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tighter mb-4">Terms of Service</h1>
          <p className="text-zinc-500 font-mono text-xs uppercase tracking-widest">Effective Date: {new Date().toLocaleDateString()} // VER: 1.0.0</p>
        </header>

        <div className="prose prose-invert prose-lg max-w-none prose-headings:font-black prose-headings:tracking-tighter prose-a:text-axim-purple hover:prose-a:text-axim-gold prose-a:transition-colors">
          <p>Welcome to AXiM Systems ("AXiM," "we," "us," or "our"). By accessing or using the AXiM Hub, our generative tools, intelligence feeds, or related infrastructure (collectively, the "Services"), you agree to be bound by these Terms of Service.</p>

          <h3>1. Core Infrastructure & Access</h3>
          <p>AXiM Systems provides an intelligent business ecosystem encompassing decentralized software tools, automated document generation, and aggregated industry intelligence. Access to specific Product Suites requires valid authorization.</p>

          <h3>2. Generative Tools & Liability Exclusions</h3>
          <p>The AXiM platform provides automated generation tools for administrative documents. <strong>These tools do not constitute legal, financial, or tax advice.</strong></p>
          <ul>
            <li>AXiM is not a law firm or an accounting firm.</li>
            <li>All generated outputs are provided "AS-IS" without warranties of compliance with local, state, or federal jurisdictions.</li>
            <li>The Operator (you) assumes 100% of the liability and risk associated with deploying, signing, or executing documents generated by our systems.</li>
          </ul>

          <h3>3. Autonomous Engine & Local Data</h3>
          <p>The AXiM Hub is designed as an autonomous edge node. In the event of network degradation, your actions may be queued and stored locally within your browser's persistent storage (Local Buffer) until a secure uplink is re-established. You are solely responsible for the physical and digital security of the device used to access the platform. AXiM is not responsible for data lost due to local cache clearing or device compromise.</p>

          <h3>4. Intelligence Feeds & Affiliate Disclosures</h3>
          <p>The "Articles" and "Intelligence Feeds" provided on AXiM.US.COM aggregate industry insights. Certain links within these reports may be affiliate links. If you utilize an affiliate link to purchase a third-party product or service, AXiM Systems may receive a commission at no additional cost to you.</p>

          <h3>5. Acceptable Use</h3>
          <p>Operators must utilize the platform for legitimate business operations. You explicitly agree <strong>NOT</strong> to deploy automated scrapers against our endpoints, or utilize our generative tools to commit fraud, misrepresent financial standing, or engage in any illicit activity.</p>
        </div>
      </motion.div>
    </div>
  );
}
