name = "axim-seo-worker"
main = "seo-worker.js"
compatibility_date = "2024-03-20"

# Uncomment and update for production custom domain routing.
# routes = [
#   { pattern = "axim.us.com/*", custom_domain = true }
# ]

[[kv_namespaces]]
binding = "FRONTEND_SEO_CACHE"
id = "ce6cf5a77ca2415a9941cc0247b86d6e"

[[kv_namespaces]]
binding = "AXIM_CONFIG"
id = "<YOUR_NAMESPACE_ID_HERE>"
