name = "axim-rpc-worker"
main = "rpc-worker.js"
compatibility_date = "2026-08-01"

[[routes]]
pattern = "rpc.axim.us.com"
custom_domain = true

# Configure securely with:
# wrangler secret put ALCHEMY_RPC_URL

[[kv_namespaces]]
binding = "WEB3_RPC_CACHE"
id = "1fe3e2e590094e638700b4b328ebabf0"
