name = "axim-seo-worker"
main = "seo-worker.js"
compatibility_date = "2026-08-01"

[[routes]]
pattern = "axim.us.com/*"
zone_name = "axim.us.com"

[[kv_namespaces]]
binding = "FRONTEND_SEO_CACHE"
id = "ce6cf5a77ca2415a9941cc0247b86d6e"

[[kv_namespaces]]
binding = "AXIM_CONFIG"
id = "AXIM_CONFIG_ID"
