name = "axim-rpc-worker"
main = "rpc-worker.js"
compatibility_date = "2024-03-20"

# Uncomment and update for production custom domain routing.
# routes = [
#   { pattern = "rpc.axim.us.com/*", custom_domain = true }
# ]

# Configure securely with:
# wrangler secret put ALCHEMY_RPC_URL
